Fixed multiple line Regexp literal to not generate invalid syntax as JavaScript
Currently, the following ruby code is compiled to invalid syntax as a
JavaScript code by Opal.

```ruby
 # test.rb
x = /re
/
```

```sh
$ opal test.rb
/tmp/opal-nodejs-runner-20170109-25185-cupfor:20157
  return (x = /re
              ^
SyntaxError: Invalid regular expression: missing /
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

$ opal -cO test.rb
/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var self = Opal.top, $scope = Opal, $scopes = [Opal], nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, x = nil;

  return (x = /re
/)
})(Opal);

/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var self = Opal.top, $scope = Opal, $scopes = [Opal], nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$exit']);
  return Opal.const_get($scopes, 'Kernel', true, true).$exit()
})(Opal);
```

Ruby allows new line(s) in a regexp literal.
However, JavaScript does not allow it.

Currently Opal optimizes a simple regexp literal.
The simple literal includes the above literal that includes a new line.
So, it's incorrectly optimized.

This change fixes the problem.